### ISSUE TITLE
pikaday not working on mobile  browser

### ISSUE THREAD

**Issue by slade991** [drew-y/meteor-pikaday-time#1]
Hey,
i hope you will see this issue. The datetime plugin isn't working on mobile browser.
There is already a fix on the pikaday official package, see this thread:

[https://github.com/dbushell/Pikaday/issues/68](https://github.com/dbushell/Pikaday/issues/68)

They say it's already commited to master, if not, it seems to be a few lines to changes. If you could mirrors the change into your meteor package. That would be awesome.

Thanks :)

**Comment by drew-y** [comment]
Try it now. Just updated the repo. However I only merged in the latest commit from [owenmead/Pikaday](https://github.com/owenmead/Pikaday) so I'm not sure if that includes the changes you are looking for. I don't use this package anymore personally so I haven't kept up with the news, owenmead used to be the only active project. Looks like that might no longer be the case.

**Comment by slade991** [comment]
Great!
It fixed the issue. Thanks for your reactivity!
